// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDje4gXxYaYFnms9bSJeEQzQ2wl1IKZWks',
    appId: '1:675754179401:web:29d77c79966c01ecaaf898',
    messagingSenderId: '675754179401',
    projectId: 'library-9e7fb',
    authDomain: 'library-9e7fb.firebaseapp.com',
    databaseURL: 'https://library-9e7fb-default-rtdb.firebaseio.com',
    storageBucket: 'library-9e7fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARBAP45Zt6PXPQIh8TKe5P7FNdBXA1Elk',
    appId: '1:675754179401:android:6fc9749e34743990aaf898',
    messagingSenderId: '675754179401',
    projectId: 'library-9e7fb',
    databaseURL: 'https://library-9e7fb-default-rtdb.firebaseio.com',
    storageBucket: 'library-9e7fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlrm1XaiGl5ctmerR7uPE0x7Izw7EgQGE',
    appId: '1:675754179401:ios:dde7a1dc9b77cd50aaf898',
    messagingSenderId: '675754179401',
    projectId: 'library-9e7fb',
    databaseURL: 'https://library-9e7fb-default-rtdb.firebaseio.com',
    storageBucket: 'library-9e7fb.appspot.com',
    iosBundleId: 'com.example.majlisLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlrm1XaiGl5ctmerR7uPE0x7Izw7EgQGE',
    appId: '1:675754179401:ios:e4c371f1d3d8c3afaaf898',
    messagingSenderId: '675754179401',
    projectId: 'library-9e7fb',
    databaseURL: 'https://library-9e7fb-default-rtdb.firebaseio.com',
    storageBucket: 'library-9e7fb.appspot.com',
    iosBundleId: 'com.example.majlisLibrary.RunnerTests',
  );
}
